//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItextSharpIkonTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadParameters", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UploadParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFxIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentFileField;
        
        private System.DateTime UploadDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UploadingUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RFxId {
            get {
                return this.RFxIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RFxIdField, value) != true)) {
                    this.RFxIdField = value;
                    this.RaisePropertyChanged("RFxId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocumentDescription {
            get {
                return this.DocumentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDescriptionField, value) != true)) {
                    this.DocumentDescriptionField = value;
                    this.RaisePropertyChanged("DocumentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] DocumentFile {
            get {
                return this.DocumentFileField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentFileField, value) != true)) {
                    this.DocumentFileField = value;
                    this.RaisePropertyChanged("DocumentFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime UploadDateTime {
            get {
                return this.UploadDateTimeField;
            }
            set {
                if ((this.UploadDateTimeField.Equals(value) != true)) {
                    this.UploadDateTimeField = value;
                    this.RaisePropertyChanged("UploadDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UploadingUserId {
            get {
                return this.UploadingUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UploadingUserIdField, value) != true)) {
                    this.UploadingUserIdField = value;
                    this.RaisePropertyChanged("UploadingUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ProcessName {
            get {
                return this.ProcessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessNameField, value) != true)) {
                    this.ProcessNameField = value;
                    this.RaisePropertyChanged("ProcessName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UploadOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIdField, value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadParameters", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DownloadParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIdField, value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DownloadOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentSize {
            get {
                return this.DocumentSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentSizeField, value) != true)) {
                    this.DocumentSizeField = value;
                    this.RaisePropertyChanged("DocumentSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] DocumentFile {
            get {
                return this.DocumentFileField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentFileField, value) != true)) {
                    this.DocumentFileField = value;
                    this.RaisePropertyChanged("DocumentFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToPdfParameters", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ToPdfParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] DocumentFile {
            get {
                return this.DocumentFileField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentFileField, value) != true)) {
                    this.DocumentFileField = value;
                    this.RaisePropertyChanged("DocumentFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToPdfOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ToPdfOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentSize {
            get {
                return this.DocumentSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentSizeField, value) != true)) {
                    this.DocumentSizeField = value;
                    this.RaisePropertyChanged("DocumentSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] DocumentFile {
            get {
                return this.DocumentFileField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentFileField, value) != true)) {
                    this.DocumentFileField = value;
                    this.RaisePropertyChanged("DocumentFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDocumentParameters", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UpdateDocumentParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewDocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] NewDocumentFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatingUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIdField, value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NewDocumentName {
            get {
                return this.NewDocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NewDocumentNameField, value) != true)) {
                    this.NewDocumentNameField = value;
                    this.RaisePropertyChanged("NewDocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] NewDocumentFile {
            get {
                return this.NewDocumentFileField;
            }
            set {
                if ((object.ReferenceEquals(this.NewDocumentFileField, value) != true)) {
                    this.NewDocumentFileField = value;
                    this.RaisePropertyChanged("NewDocumentFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UpdatingUserId {
            get {
                return this.UpdatingUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatingUserIdField, value) != true)) {
                    this.UpdatingUserIdField = value;
                    this.RaisePropertyChanged("UpdatingUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDocumentOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UpdateDocumentOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfUpdateParameters", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PdfUpdateParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PDFContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PDFNameField;
        
        private bool ToAllPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ItextSharpIkonTest.ServiceReference1.ArrayOfInt PageNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ItextSharpIkonTest.ServiceReference1.InfoToBePrinted InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] PDFContent {
            get {
                return this.PDFContentField;
            }
            set {
                if ((object.ReferenceEquals(this.PDFContentField, value) != true)) {
                    this.PDFContentField = value;
                    this.RaisePropertyChanged("PDFContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PDFName {
            get {
                return this.PDFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PDFNameField, value) != true)) {
                    this.PDFNameField = value;
                    this.RaisePropertyChanged("PDFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ToAllPages {
            get {
                return this.ToAllPagesField;
            }
            set {
                if ((this.ToAllPagesField.Equals(value) != true)) {
                    this.ToAllPagesField = value;
                    this.RaisePropertyChanged("ToAllPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ItextSharpIkonTest.ServiceReference1.ArrayOfInt PageNumbers {
            get {
                return this.PageNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.PageNumbersField, value) != true)) {
                    this.PageNumbersField = value;
                    this.RaisePropertyChanged("PageNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ItextSharpIkonTest.ServiceReference1.InfoToBePrinted Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoToBePrinted", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InfoToBePrinted : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmationInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FontNameField;
        
        private int FontSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTMLColorField;
        
        private int PDF_XField;
        
        private int PDF_YField;
        
        private int TextWidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ConfirmationInfo {
            get {
                return this.ConfirmationInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmationInfoField, value) != true)) {
                    this.ConfirmationInfoField = value;
                    this.RaisePropertyChanged("ConfirmationInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FontName {
            get {
                return this.FontNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FontNameField, value) != true)) {
                    this.FontNameField = value;
                    this.RaisePropertyChanged("FontName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FontSize {
            get {
                return this.FontSizeField;
            }
            set {
                if ((this.FontSizeField.Equals(value) != true)) {
                    this.FontSizeField = value;
                    this.RaisePropertyChanged("FontSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HTMLColor {
            get {
                return this.HTMLColorField;
            }
            set {
                if ((object.ReferenceEquals(this.HTMLColorField, value) != true)) {
                    this.HTMLColorField = value;
                    this.RaisePropertyChanged("HTMLColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PDF_X {
            get {
                return this.PDF_XField;
            }
            set {
                if ((this.PDF_XField.Equals(value) != true)) {
                    this.PDF_XField = value;
                    this.RaisePropertyChanged("PDF_X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PDF_Y {
            get {
                return this.PDF_YField;
            }
            set {
                if ((this.PDF_YField.Equals(value) != true)) {
                    this.PDF_YField = value;
                    this.RaisePropertyChanged("PDF_Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TextWidth {
            get {
                return this.TextWidthField;
            }
            set {
                if ((this.TextWidthField.Equals(value) != true)) {
                    this.TextWidthField = value;
                    this.RaisePropertyChanged("TextWidth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfUpdateOperationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PdfUpdateOperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewDocumentSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] NewDocumentFileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NewDocumentSize {
            get {
                return this.NewDocumentSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.NewDocumentSizeField, value) != true)) {
                    this.NewDocumentSizeField = value;
                    this.RaisePropertyChanged("NewDocumentSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] NewDocumentFile {
            get {
                return this.NewDocumentFileField;
            }
            set {
                if ((object.ReferenceEquals(this.NewDocumentFileField, value) != true)) {
                    this.NewDocumentFileField = value;
                    this.RaisePropertyChanged("NewDocumentFile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FileManagerServiceSoap")]
    public interface FileManagerServiceSoap {
        
        // CODEGEN: Generating message contract since element name uploadParameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        ItextSharpIkonTest.ServiceReference1.UploadFileResponse UploadFile(ItextSharpIkonTest.ServiceReference1.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name downloadParameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadFile", ReplyAction="*")]
        ItextSharpIkonTest.ServiceReference1.DownloadFileResponse DownloadFile(ItextSharpIkonTest.ServiceReference1.DownloadFileRequest request);
        
        // CODEGEN: Generating message contract since element name toPdfParameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToPdf", ReplyAction="*")]
        ItextSharpIkonTest.ServiceReference1.ConvertToPdfResponse ConvertToPdf(ItextSharpIkonTest.ServiceReference1.ConvertToPdfRequest request);
        
        // CODEGEN: Generating message contract since element name updateDocParameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDocument", ReplyAction="*")]
        ItextSharpIkonTest.ServiceReference1.UpdateDocumentResponse UpdateDocument(ItextSharpIkonTest.ServiceReference1.UpdateDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name updateDocParameters from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PdfUpdate", ReplyAction="*")]
        ItextSharpIkonTest.ServiceReference1.PdfUpdateResponse PdfUpdate(ItextSharpIkonTest.ServiceReference1.PdfUpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(ItextSharpIkonTest.ServiceReference1.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UploadParameters uploadParameters;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(ItextSharpIkonTest.ServiceReference1.UploadParameters uploadParameters) {
            this.uploadParameters = uploadParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(ItextSharpIkonTest.ServiceReference1.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UploadOperationResult UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(ItextSharpIkonTest.ServiceReference1.UploadOperationResult UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadFile", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.DownloadFileRequestBody Body;
        
        public DownloadFileRequest() {
        }
        
        public DownloadFileRequest(ItextSharpIkonTest.ServiceReference1.DownloadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.DownloadParameters downloadParameters;
        
        public DownloadFileRequestBody() {
        }
        
        public DownloadFileRequestBody(ItextSharpIkonTest.ServiceReference1.DownloadParameters downloadParameters) {
            this.downloadParameters = downloadParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.DownloadFileResponseBody Body;
        
        public DownloadFileResponse() {
        }
        
        public DownloadFileResponse(ItextSharpIkonTest.ServiceReference1.DownloadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.DownloadOperationResult DownloadFileResult;
        
        public DownloadFileResponseBody() {
        }
        
        public DownloadFileResponseBody(ItextSharpIkonTest.ServiceReference1.DownloadOperationResult DownloadFileResult) {
            this.DownloadFileResult = DownloadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToPdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToPdf", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.ConvertToPdfRequestBody Body;
        
        public ConvertToPdfRequest() {
        }
        
        public ConvertToPdfRequest(ItextSharpIkonTest.ServiceReference1.ConvertToPdfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToPdfRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.ToPdfParameters toPdfParameters;
        
        public ConvertToPdfRequestBody() {
        }
        
        public ConvertToPdfRequestBody(ItextSharpIkonTest.ServiceReference1.ToPdfParameters toPdfParameters) {
            this.toPdfParameters = toPdfParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToPdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToPdfResponse", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.ConvertToPdfResponseBody Body;
        
        public ConvertToPdfResponse() {
        }
        
        public ConvertToPdfResponse(ItextSharpIkonTest.ServiceReference1.ConvertToPdfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToPdfResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.ToPdfOperationResult ConvertToPdfResult;
        
        public ConvertToPdfResponseBody() {
        }
        
        public ConvertToPdfResponseBody(ItextSharpIkonTest.ServiceReference1.ToPdfOperationResult ConvertToPdfResult) {
            this.ConvertToPdfResult = ConvertToPdfResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDocument", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UpdateDocumentRequestBody Body;
        
        public UpdateDocumentRequest() {
        }
        
        public UpdateDocumentRequest(ItextSharpIkonTest.ServiceReference1.UpdateDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UpdateDocumentParameters updateDocParameters;
        
        public UpdateDocumentRequestBody() {
        }
        
        public UpdateDocumentRequestBody(ItextSharpIkonTest.ServiceReference1.UpdateDocumentParameters updateDocParameters) {
            this.updateDocParameters = updateDocParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UpdateDocumentResponseBody Body;
        
        public UpdateDocumentResponse() {
        }
        
        public UpdateDocumentResponse(ItextSharpIkonTest.ServiceReference1.UpdateDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.UpdateDocumentOperationResult UpdateDocumentResult;
        
        public UpdateDocumentResponseBody() {
        }
        
        public UpdateDocumentResponseBody(ItextSharpIkonTest.ServiceReference1.UpdateDocumentOperationResult UpdateDocumentResult) {
            this.UpdateDocumentResult = UpdateDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PdfUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PdfUpdate", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.PdfUpdateRequestBody Body;
        
        public PdfUpdateRequest() {
        }
        
        public PdfUpdateRequest(ItextSharpIkonTest.ServiceReference1.PdfUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PdfUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.PdfUpdateParameters updateDocParameters;
        
        public PdfUpdateRequestBody() {
        }
        
        public PdfUpdateRequestBody(ItextSharpIkonTest.ServiceReference1.PdfUpdateParameters updateDocParameters) {
            this.updateDocParameters = updateDocParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PdfUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PdfUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ItextSharpIkonTest.ServiceReference1.PdfUpdateResponseBody Body;
        
        public PdfUpdateResponse() {
        }
        
        public PdfUpdateResponse(ItextSharpIkonTest.ServiceReference1.PdfUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PdfUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ItextSharpIkonTest.ServiceReference1.PdfUpdateOperationResult PdfUpdateResult;
        
        public PdfUpdateResponseBody() {
        }
        
        public PdfUpdateResponseBody(ItextSharpIkonTest.ServiceReference1.PdfUpdateOperationResult PdfUpdateResult) {
            this.PdfUpdateResult = PdfUpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileManagerServiceSoapChannel : ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileManagerServiceSoapClient : System.ServiceModel.ClientBase<ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap>, ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap {
        
        public FileManagerServiceSoapClient() {
        }
        
        public FileManagerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileManagerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileManagerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileManagerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ItextSharpIkonTest.ServiceReference1.UploadFileResponse ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap.UploadFile(ItextSharpIkonTest.ServiceReference1.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public ItextSharpIkonTest.ServiceReference1.UploadOperationResult UploadFile(ItextSharpIkonTest.ServiceReference1.UploadParameters uploadParameters) {
            ItextSharpIkonTest.ServiceReference1.UploadFileRequest inValue = new ItextSharpIkonTest.ServiceReference1.UploadFileRequest();
            inValue.Body = new ItextSharpIkonTest.ServiceReference1.UploadFileRequestBody();
            inValue.Body.uploadParameters = uploadParameters;
            ItextSharpIkonTest.ServiceReference1.UploadFileResponse retVal = ((ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ItextSharpIkonTest.ServiceReference1.DownloadFileResponse ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap.DownloadFile(ItextSharpIkonTest.ServiceReference1.DownloadFileRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public ItextSharpIkonTest.ServiceReference1.DownloadOperationResult DownloadFile(ItextSharpIkonTest.ServiceReference1.DownloadParameters downloadParameters) {
            ItextSharpIkonTest.ServiceReference1.DownloadFileRequest inValue = new ItextSharpIkonTest.ServiceReference1.DownloadFileRequest();
            inValue.Body = new ItextSharpIkonTest.ServiceReference1.DownloadFileRequestBody();
            inValue.Body.downloadParameters = downloadParameters;
            ItextSharpIkonTest.ServiceReference1.DownloadFileResponse retVal = ((ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap)(this)).DownloadFile(inValue);
            return retVal.Body.DownloadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ItextSharpIkonTest.ServiceReference1.ConvertToPdfResponse ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap.ConvertToPdf(ItextSharpIkonTest.ServiceReference1.ConvertToPdfRequest request) {
            return base.Channel.ConvertToPdf(request);
        }
        
        public ItextSharpIkonTest.ServiceReference1.ToPdfOperationResult ConvertToPdf(ItextSharpIkonTest.ServiceReference1.ToPdfParameters toPdfParameters) {
            ItextSharpIkonTest.ServiceReference1.ConvertToPdfRequest inValue = new ItextSharpIkonTest.ServiceReference1.ConvertToPdfRequest();
            inValue.Body = new ItextSharpIkonTest.ServiceReference1.ConvertToPdfRequestBody();
            inValue.Body.toPdfParameters = toPdfParameters;
            ItextSharpIkonTest.ServiceReference1.ConvertToPdfResponse retVal = ((ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap)(this)).ConvertToPdf(inValue);
            return retVal.Body.ConvertToPdfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ItextSharpIkonTest.ServiceReference1.UpdateDocumentResponse ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap.UpdateDocument(ItextSharpIkonTest.ServiceReference1.UpdateDocumentRequest request) {
            return base.Channel.UpdateDocument(request);
        }
        
        public ItextSharpIkonTest.ServiceReference1.UpdateDocumentOperationResult UpdateDocument(ItextSharpIkonTest.ServiceReference1.UpdateDocumentParameters updateDocParameters) {
            ItextSharpIkonTest.ServiceReference1.UpdateDocumentRequest inValue = new ItextSharpIkonTest.ServiceReference1.UpdateDocumentRequest();
            inValue.Body = new ItextSharpIkonTest.ServiceReference1.UpdateDocumentRequestBody();
            inValue.Body.updateDocParameters = updateDocParameters;
            ItextSharpIkonTest.ServiceReference1.UpdateDocumentResponse retVal = ((ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap)(this)).UpdateDocument(inValue);
            return retVal.Body.UpdateDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ItextSharpIkonTest.ServiceReference1.PdfUpdateResponse ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap.PdfUpdate(ItextSharpIkonTest.ServiceReference1.PdfUpdateRequest request) {
            return base.Channel.PdfUpdate(request);
        }
        
        public ItextSharpIkonTest.ServiceReference1.PdfUpdateOperationResult PdfUpdate(ItextSharpIkonTest.ServiceReference1.PdfUpdateParameters updateDocParameters) {
            ItextSharpIkonTest.ServiceReference1.PdfUpdateRequest inValue = new ItextSharpIkonTest.ServiceReference1.PdfUpdateRequest();
            inValue.Body = new ItextSharpIkonTest.ServiceReference1.PdfUpdateRequestBody();
            inValue.Body.updateDocParameters = updateDocParameters;
            ItextSharpIkonTest.ServiceReference1.PdfUpdateResponse retVal = ((ItextSharpIkonTest.ServiceReference1.FileManagerServiceSoap)(this)).PdfUpdate(inValue);
            return retVal.Body.PdfUpdateResult;
        }
    }
}
